@startuml
class ContactoExcepcion {
- String mensaje
+ String getMessage()
+ String toString()
}
class ContactoProfesionalExcepcion {
}



IOException <|-- ContactoExcepcion
ContactoExcepcion <|-- ContactoProfesionalExcepcion
@enduml